### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by darxriggs**
- proper naming
- proper formatting
- less mutability

### CODE REVIEW

**Comment by darxriggs** [comment]
@jvz That's it with planned changes from my side.

Do you think a release makes sense? I guess there are no other changes planned in the near future.

**Comment by jvz** [comment]
Someone recently filed https://issues.jenkins-ci.org/browse/JENKINS-59545 which may or may not need a fix. A release can likely be done after merging this, though.

**Comment by jvz** [comment]
@darxriggs I just made a 1.6 release with this and #13 included.

**Comment by darxriggs** [comment]
@jvz Thanks.

**Pull request merged**
