### PR TITLE
Add JCasC integration test

### PR DESCRIPTION
**Pull request by jvz**
This is a fairly simple plugin configuration-wise as it simply chooses which PAM service to use for authenticating users. The default is `sshd` which sort of makes sense without a specific `/etc/pam.d/jenkins` config file.

### CODE REVIEW

**Comment by jvz** [comment]
Seems like a CI issue.

**Comment by jvz** [comment]
Current test failure is due to the default build configuration. Let me see if I can update that.

**Comment by Wadeck** [comment]
Got the same failure locally

<details>

<summary>Trace</summary>

<pre>
=== Starting testConfigYaml(hudson.security.PAMSecurityRealmJCasCTest)
  13.838 [id=13]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:9196/jenkins/
  18.703 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
  19.722 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
  23.785 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
  23.795 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
  23.798 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
  28.939 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
  29.032 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
  29.033 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
  29.035 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
  29.811 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization

java.lang.AssertionError: Unexpected exception 

	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:50)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:589)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for pam
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:211)
	at io.vavr.control.Option.orElse(Option.java:321)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:210)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:84)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:351)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:585)
	at io.jenkins.plugins.casc.misc.JenkinsConfiguredWithCodeRule.before(JenkinsConfiguredWithCodeRule.java:47)
	... 5 more


</pre>

</details>

**Comment by alecharp** [comment]
I come here late, but having the plugin checked against Java 8 and Java 11 would still have been great.

**Comment by jvz** [comment]
@alecharp what build configuration should I use that will also be compatible with JCasC? The current default recommended build settings are too old.

**Pull request merged**
