### PR TITLE
avoid use of PosixAPI

### PR DESCRIPTION
**Pull request by ndeloof**
@jenkinsci/java10-support

### CODE REVIEW

**Comment by jglick** [comment]
cf. #2, since GH does not do auto linking from review summaries, sigh

**Comment by joerg** [comment]
+1 for a merge! This will finally not use /etc/shadow any more which has nothing to do with PAM anyway.

**Comment by jvz** [comment]
@jenkinsci/code-reviewers can I get a verification?

**Comment by ndeloof** [comment]
inactive, feel free to take over

**Pull request closed without merging**
